"""
Test Fixtures for Phase 5 Drainage Network Engine.

CRITICAL REQUIREMENT:
All synthetic drainage networks generated by these fixtures are strictly labeled:
'TEST FIXTURE ONLY'. They must NEVER be used or represented as real operational municipal infrastructure.
"""

from typing import Any

import pytest
from app.geospatial.drainage import DirectionStatus, LinkType, NodeType

FIXTURE_LABEL = "TEST FIXTURE ONLY — Synthetic Test Fixture"


@pytest.fixture
def simple_chain_network() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Linear N1 -> N2 -> N3 -> OUT1 network."""
    nodes = [
        {"node_id": "N1", "node_type": NodeType.INLET.value, "x": 500000.0, "y": 4501000.0, "elevation_m": 100.0},
        {"node_id": "N2", "node_type": NodeType.MANHOLE.value, "x": 500100.0, "y": 4501000.0, "elevation_m": 95.0},
        {"node_id": "N3", "node_type": NodeType.JUNCTION.value, "x": 500200.0, "y": 4501000.0, "elevation_m": 90.0},
        {"node_id": "OUT1", "node_type": NodeType.OUTFALL.value, "x": 500300.0, "y": 4501000.0, "elevation_m": 85.0},
    ]
    links = [
        {"link_id": "L1", "from_node_id": "N1", "to_node_id": "N2", "link_type": LinkType.PIPE.value, "length_m": 100.0, "coords": [(500000.0, 4501000.0), (500100.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value, "capacity_m3s": 1.5},
        {"link_id": "L2", "from_node_id": "N2", "to_node_id": "N3", "link_type": LinkType.PIPE.value, "length_m": 100.0, "coords": [(500100.0, 4501000.0), (500200.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value, "capacity_m3s": 2.5},
        {"link_id": "L3", "from_node_id": "N3", "to_node_id": "OUT1", "link_type": LinkType.CONDUIT.value, "length_m": 100.0, "coords": [(500200.0, 4501000.0), (500300.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value, "capacity_m3s": 4.0},
    ]
    return nodes, links


@pytest.fixture
def branching_network() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Branching network N1 -> N3, N2 -> N3 -> OUT1."""
    nodes = [
        {"node_id": "N1", "node_type": NodeType.INLET.value, "x": 500000.0, "y": 4501100.0},
        {"node_id": "N2", "node_type": NodeType.INLET.value, "x": 500000.0, "y": 4500900.0},
        {"node_id": "N3", "node_type": NodeType.JUNCTION.value, "x": 500200.0, "y": 4501000.0},
        {"node_id": "OUT1", "node_type": NodeType.OUTFALL.value, "x": 500400.0, "y": 4501000.0},
    ]
    links = [
        {"link_id": "L1", "from_node_id": "N1", "to_node_id": "N3", "link_type": LinkType.PIPE.value, "length_m": 223.6, "coords": [(500000.0, 4501100.0), (500200.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value},
        {"link_id": "L2", "from_node_id": "N2", "to_node_id": "N3", "link_type": LinkType.PIPE.value, "length_m": 223.6, "coords": [(500000.0, 4500900.0), (500200.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value},
        {"link_id": "L3", "from_node_id": "N3", "to_node_id": "OUT1", "link_type": LinkType.OPEN_CHANNEL.value, "length_m": 200.0, "coords": [(500200.0, 4501000.0), (500400.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value},
    ]
    return nodes, links


@pytest.fixture
def disconnected_network() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Network with 2 disconnected components: N1->OUT1 and X1->X2 (unreachable outfall)."""
    nodes = [
        {"node_id": "N1", "node_type": NodeType.INLET.value, "x": 500000.0, "y": 4501000.0},
        {"node_id": "OUT1", "node_type": NodeType.OUTFALL.value, "x": 500100.0, "y": 4501000.0},
        {"node_id": "X1", "node_type": NodeType.MANHOLE.value, "x": 505000.0, "y": 4505000.0},
        {"node_id": "X2", "node_type": NodeType.MANHOLE.value, "x": 505100.0, "y": 4505000.0},
    ]
    links = [
        {"link_id": "L1", "from_node_id": "N1", "to_node_id": "OUT1", "link_type": LinkType.PIPE.value, "length_m": 100.0, "coords": [(500000.0, 4501000.0), (500100.0, 4501000.0)], "direction_status": DirectionStatus.KNOWN.value},
        {"link_id": "LX", "from_node_id": "X1", "to_node_id": "X2", "link_type": LinkType.PIPE.value, "length_m": 100.0, "coords": [(505000.0, 4505000.0), (505100.0, 4505000.0)], "direction_status": DirectionStatus.KNOWN.value},
    ]
    return nodes, links
