"""
Test Fixtures for Phase 4 Terrain & Surface-Flow Engine.

CRITICAL REQUIREMENT:
All synthetic DEM rasters generated by these fixtures are strictly labeled:
'TEST FIXTURE ONLY'. They must NEVER be used or represented as real operational terrain.
"""

from typing import Any

import numpy as np
import pytest
from rasterio.transform import Affine

FIXTURE_LABEL = "TEST FIXTURE ONLY — Synthetic Test Fixture"


@pytest.fixture
def flat_dem_fixture() -> tuple[np.ndarray, dict[str, Any]]:
    """10x10 uniform flat plane DEM (100.0 m elevation)."""
    width, height, resolution = 10, 10, 10.0
    transform = Affine.translation(500000.0, 4501000.0) * Affine.scale(resolution, -resolution)
    elevation = np.full((height, width), 100.0, dtype=np.float32)
    metadata = {
        "dataset_id": "test_flat_plane",
        "source": FIXTURE_LABEL,
        "crs": "EPSG:32633",
        "transform": [transform.a, transform.b, transform.c, transform.d, transform.e, transform.f],
        "bounds": (500000.0, 4501000.0 - height * resolution, 500000.0 + width * resolution, 4501000.0),
        "width": width,
        "height": height,
        "resolution": (resolution, resolution),
        "vertical_units": "meters",
        "nodata": -9999.0,
        "is_test_fixture": True,
        "provenance": {"label": FIXTURE_LABEL}
    }
    return elevation, metadata


@pytest.fixture
def inclined_plane_fixture() -> tuple[np.ndarray, dict[str, Any]]:
    """
    10x10 inclined plane descending North (row 0, elev 100m) to South (row 9, elev 55m).
    Drop per cell = 5.0 m over dx = 10.0 m -> slope = arctan(5/10) = 26.565°.
    """
    width, height, resolution = 10, 10, 10.0
    transform = Affine.translation(500000.0, 4501000.0) * Affine.scale(resolution, -resolution)
    rows = np.linspace(100.0, 55.0, height, dtype=np.float32)
    elevation = np.tile(rows[:, np.newaxis], (1, width))
    metadata = {
        "dataset_id": "test_inclined_plane",
        "source": FIXTURE_LABEL,
        "crs": "EPSG:32633",
        "transform": [transform.a, transform.b, transform.c, transform.d, transform.e, transform.f],
        "bounds": (500000.0, 4501000.0 - height * resolution, 500000.0 + width * resolution, 4501000.0),
        "width": width,
        "height": height,
        "resolution": (resolution, resolution),
        "vertical_units": "meters",
        "nodata": -9999.0,
        "is_test_fixture": True,
        "provenance": {"label": FIXTURE_LABEL}
    }
    return elevation, metadata


@pytest.fixture
def v_valley_fixture() -> tuple[np.ndarray, dict[str, Any]]:
    """10x10 V-shaped valley sloping down to central column (col 5)."""
    width, height, resolution = 10, 10, 10.0
    transform = Affine.translation(500000.0, 4501000.0) * Affine.scale(resolution, -resolution)
    cols = np.abs(np.arange(width) - 5.0).astype(np.float32) * 5.0
    rows = np.linspace(50.0, 10.0, height, dtype=np.float32)
    elevation = cols[np.newaxis, :] + rows[:, np.newaxis]
    metadata = {
        "dataset_id": "test_v_valley",
        "source": FIXTURE_LABEL,
        "crs": "EPSG:32633",
        "transform": [transform.a, transform.b, transform.c, transform.d, transform.e, transform.f],
        "bounds": (500000.0, 4501000.0 - height * resolution, 500000.0 + width * resolution, 4501000.0),
        "width": width,
        "height": height,
        "resolution": (resolution, resolution),
        "vertical_units": "meters",
        "nodata": -9999.0,
        "is_test_fixture": True,
        "provenance": {"label": FIXTURE_LABEL}
    }
    return elevation, metadata


@pytest.fixture
def sink_depression_fixture() -> tuple[np.ndarray, dict[str, Any]]:
    """10x10 plane with a central local depression/sink."""
    width, height, resolution = 10, 10, 10.0
    transform = Affine.translation(500000.0, 4501000.0) * Affine.scale(resolution, -resolution)
    elevation = np.full((height, width), 100.0, dtype=np.float32)
    elevation[4:7, 4:7] = 80.0
    elevation[5, 5] = 60.0  # Center sink cell
    metadata = {
        "dataset_id": "test_sink_depression",
        "source": FIXTURE_LABEL,
        "crs": "EPSG:32633",
        "transform": [transform.a, transform.b, transform.c, transform.d, transform.e, transform.f],
        "bounds": (500000.0, 4501000.0 - height * resolution, 500000.0 + width * resolution, 4501000.0),
        "width": width,
        "height": height,
        "resolution": (resolution, resolution),
        "vertical_units": "meters",
        "nodata": -9999.0,
        "is_test_fixture": True,
        "provenance": {"label": FIXTURE_LABEL}
    }
    return elevation, metadata
